name: Builder

on:

  push

jobs:

  builder:

      runs-on: ubuntu-latest

      steps:

        - name: test

          run: |
            echo "start"
            curl https://raw.githubusercontent.com/zmzu/ci-rom-build/lineage-14.1-wt88047/builder.sh > builder.sh && bash builder.sh

            
